### ISSUE TITLE
[OJS 3.1.2] Plugin fails on saving Section Browsing

### ISSUE THREAD

**Issue by mpbraendle** [pkp/browseBySection#16]
OJS 3.1.2, all schemas updated after installation of plugin.
The Plugin fails after the form in a section has been completed and Save button is pressed.

Error log: 
[15-Mar-2019 10:31:10 UTC] PHP Notice:  Undefined offset: 2 in /usr/local/service/www/ojs/plugins/generic/browseBySection/BrowseBySectionPlugin.inc.php on line 190
[15-Mar-2019 10:31:10 UTC] PHP Fatal error:  Uncaught Error: Call to a member function setData() on null in /usr/local/service/www/ojs/plugins/generic/browseBySection/BrowseBySectionPlugin.inc.php:192
Stack trace:
#0 /usr/local/service/www/ojs/lib/pkp/classes/plugins/HookRegistry.inc.php(107): BrowseBySectionPlugin->executeSectionFormFields('sectionform::ex...', Array)
#1 /usr/local/service/www/ojs/lib/pkp/classes/form/Form.inc.php(314): HookRegistry::call('sectionform::ex...', Array)
#2 /usr/local/service/www/ojs/controllers/grid/settings/sections/form/SectionForm.inc.php(164): Form->execute()
#3 /usr/local/service/www/ojs/controllers/grid/settings/sections/SectionGridHandler.inc.php(193): SectionForm->execute()
#4 /usr/local/service/www/ojs/lib/pkp/classes/core/PKPRouter.inc.php(390): SectionGridHandler->updateSection(Array, Object(Request))
#5 /usr/local/service/www/ojs/lib/pkp/classes/core/PKPComponentRouter.inc.php(257): PKPRouter->_authorizeInitializeAndCallRequest(Array, Object(Request), Array)
#6 /usr/local/service/www/ojs/lib/pkp/classes/core/D in /usr/local/service/www/ojs/plugins/generic/browseBySection/BrowseBySectionPlugin.inc.php on line 192
[15-Mar-2019 10:33:01 UTC] PHP Warning:  Declaration of CustomBlockPlugin::getBlockContext() should be compatible with BlockPlugin::getBlockContext($contextId = NULL) in /usr/local/service/www/ojs/plugins/generic/customBlockManager/CustomBlockPlugin.inc.php on line 0
[15-Mar-2019 10:33:01 UTC] PHP Warning:  Declaration of SectionForm::fetch($request) should be compatible with Form::fetch($request, $template = NULL, $display = false) in /usr/local/service/www/ojs/controllers/grid/settings/sections/form/SectionForm.inc.php on line 18
[15-Mar-2019 10:33:01 UTC] PHP Warning:  Declaration of CustomBlockPlugin::getBlockContext() should be compatible with BlockPlugin::getBlockContext($contextId = NULL) in /usr/local/service/www/ojs/plugins/generic/customBlockManager/CustomBlockPlugin.inc.php on line 0

**Comment by NateWr** [comment]
Thanks @mpbraendle, I've just pushed a fix for this. Update from the `master` branch to get the latest changes. We haven't made an official release of this yet so I won't put anything out, but syncing should take care of it for you on 3.1.2.

FYI, it was this change in 3.1.2 that caught me out. https://github.com/pkp/pkp-lib/issues/4612
