### ISSUE TITLE
Fatal error when trying to edit or create journal sections

### ISSUE THREAD

**Issue by Vitaliy-1** [pkp/browseBySection#18]
Tested with OJS 3.1.2-1. Only appears when the plugin is enabled.
To reproduce, in `Journal Settings -> Section` edit or create new Section.
In PHP logs:
```
[20-Jun-2019 07:00:44 UTC] PHP Fatal error:  Uncaught Error: Call to undefined method Application::get() in /var/www/ojs-3.1.2-1/plugins/generic/browseBySection/BrowseBySectionPlugin.inc.php:145
Stack trace:
#0 /var/www/ojs-3.1.2-1/lib/pkp/classes/plugins/HookRegistry.inc.php(107): BrowseBySectionPlugin->initDataSectionFormFields('sectionform::in...', Array)
#1 /var/www/ojs-3.1.2-1/lib/pkp/classes/form/Form.inc.php(240): HookRegistry::call('sectionform::in...', Array)
#2 /var/www/ojs-3.1.2-1/controllers/grid/settings/sections/form/SectionForm.inc.php(70): Form->initData()
#3 /var/www/ojs-3.1.2-1/controllers/grid/settings/sections/SectionGridHandler.inc.php(175): SectionForm->initData()
#4 /var/www/ojs-3.1.2-1/lib/pkp/classes/core/PKPRouter.inc.php(390): SectionGridHandler->editSection(Array, Object(Request))
#5 /var/www/ojs-3.1.2-1/lib/pkp/classes/core/PKPComponentRouter.inc.php(257): PKPRouter->_authorizeInitializeAndCallRequest(Array, Object(Request), Array)
#6 /var/www/ojs-3.1.2-1/lib/pkp/classes/core/Dispatcher.inc.php(134): PKPComponentRouter->rout in /var/www/ojs-3.1.2-1/plugins/generic/browseBySection/BrowseBySectionPlugin.inc.php on line 145
```

**Comment by NateWr** [comment]
Did you try with the `stable-3_1_2` branch? https://github.com/pkp/browseBySection/issues/17

**Comment by Vitaliy-1** [comment]
Yes, is resolved there.
