### ISSUE TITLE
Sitemap Page Error when browseBySection Plugin is Active

### ISSUE THREAD

**Issue by kswro** [pkp/browseBySection#36]
**Describe the bug**
Browse By Section plugin causes the sitemap page to be inaccessible (error 500) when activated. When deactivating this plugin, the sitemap page can be accessed again.

**To Reproduce**
1. Fresh Install
2. Download and activate the Browse By Section plugin
3. Access the sitemap page (ex: https://your.site/journal/sitemap)
4. HTTP Error 500

**What application are you using?**
1. OJS 3.4.0.3
2. Browse By Section 1.2.1.0
3. PHP 8.2.11

**Additional Information**
restful_urls = On

**Log**
```
PHP Fatal error:  Uncaught Error: Non-static method PKP\core\PKPApplication::getRequest() cannot be called statically in /home/.../public_html/plugins/generic/browseBySection/BrowseBySectionPlugin.php:303
Stack trace:
#0 [internal function]: APP\plugins\generic\browseBySection\BrowseBySectionPlugin->addSitemapURLs()
#1 /home/.../public_html/lib/pkp/classes/plugins/Hook.php(139): call_user_func_array()
#2 /home/.../public_html/lib/pkp/classes/plugins/Hook.php(113): PKP\plugins\Hook::run()
#3 /home/.../public_html/pages/sitemap/SitemapHandler.php(78): PKP\plugins\Hook::call()
#4 /home/.../public_html/lib/pkp/pages/sitemap/PKPSitemapHandler.php(50): APP\pages\sitemap\SitemapHandler->_createContextSitemap()
#5 [internal function]: PKP\pages\sitemap\PKPSitemapHandler->index()
#6 /home/.../public_html/lib/pkp/classes/core/PKPRouter.php(334): call_user_func()
#7 /home/.../public_html/lib/pkp/classes/core/PKPPageRouter.php(277): PKP\core\PKPRouter->_authorizeInitializeAndCallRequest()
#8 /home/.../public_html/lib/pkp/classes/core/Dispatcher.php(165): PKP\core\PKPPageRouter->route()
#9 /home/.../public_html/lib/pkp/classes/core/PKPApplication.php(387): PKP\core\Dispatcher->dispatch()
#10 /home/.../public_html/index.php(21): PKP\core\PKPApplication->execute()
#11 {main}
  thrown in /home/.../public_html/plugins/generic/browseBySection/BrowseBySectionPlugin.php on line 303
```

**Comment by kaitlinnewson** [comment]
Fixed and released for 3.3/3.4, closing.
